name: Linear GraphQL Mutation

on: workflow_dispatch

jobs:
  linear-mutation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set issue labels
        run: |
          label_uuid="9d52286c-6256-42b4-bf41-ebf3b1f8b5ff"
          curl -X POST \
            -H "Authorization: ${{ secrets.LINEAR_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"query\": \"mutation IssueAddLabel { issueAddLabel( id: \\\"LAND-420\\\", labelId: \\\"$label_uuid\\\" ) { success issue { id title state { id name } } } }\"}" \
            https://api.linear.app/graphql
